GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/persons/5

###
GET http://localhost:3001/api/persons/66e86a3f4868472d8be752ca

###
DELETE http://localhost:3001/api/persons/66e9e3b76f1d1ffc15aafab1

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Fart Man",
    "number": "(200) 222-2020"
}

###
PUT http://localhost:3001/api/persons/66e86816b442c73b3344655b
Content-Type: application/json

{
    "name": "Mr. Cheese",
    "number": "1234567890",
    "favorite": true
}

###

GET http://localhost:3001/info